!!stats!!
 { size: 9849,
  gzipSize: 2269,
  humanizedSize: '10kB',
  humanizedGzipSize: '2kB',
  rules: 
   { total: 247,
     size: { graph: [Object], max: 6, average: 1.5506072874493928 } },
  selectors: 
   { total: 256,
     type: 0,
     class: 256,
     id: 0,
     pseudoClass: 0,
     pseudoElement: 3,
     values: 
      [ '.h1',
        '.h2',
        '.h3',
        '.h4',
        '.h5',
        '.h6',
        '.font-family-inherit',
        '.font-size-inherit',
        '.text-decoration-none',
        '.bold',
        '.regular',
        '.italic',
        '.caps',
        '.left-align',
        '.center',
        '.right-align',
        '.justify',
        '.nowrap',
        '.break-word',
        '.line-height-1',
        '.line-height-2',
        '.line-height-3',
        '.line-height-4',
        '.list-style-none',
        '.underline',
        '.truncate',
        '.list-reset',
        '.inline',
        '.block',
        '.inline-block',
        '.table',
        '.table-cell',
        '.overflow-hidden',
        '.overflow-scroll',
        '.overflow-auto',
        '.clearfix:after',
        '.clearfix:before',
        '.clearfix:after',
        '.left',
        '.right',
        '.fit',
        '.max-width-1',
        '.max-width-2',
        '.max-width-3',
        '.max-width-4',
        '.border-box',
        '.align-baseline',
        '.align-top',
        '.align-middle',
        '.align-bottom',
        '.m0',
        '.mt0',
        '.mr0',
        '.mb0',
        '.ml0',
        '.mx0',
        '.mx0',
        '.my0',
        '.m1',
        '.mt1',
        '.mr1',
        '.mb1',
        '.ml1',
        '.mx1',
        '.mx1',
        '.my1',
        '.m2',
        '.mt2',
        '.mr2',
        '.mb2',
        '.ml2',
        '.mx2',
        '.mx2',
        '.my2',
        '.m3',
        '.mt3',
        '.mr3',
        '.mb3',
        '.ml3',
        '.mx3',
        '.mx3',
        '.my3',
        '.m4',
        '.mt4',
        '.mr4',
        '.mb4',
        '.ml4',
        '.mx4',
        '.mx4',
        '.my4',
        '.mxn1',
        '.mxn2',
        '.mxn3',
        '.mxn4',
        '.ml-auto',
        '.mr-auto',
        '.mx-auto',
        '.mx-auto',
        '.p0',
        '.pt0',
        ... 156 more items ],
     specificity: { max: 11, average: 10.01171875 },
     getSpecificityGraph: [Function],
     getSortedSpecificity: [Function],
     getRepeatedValues: [Function] },
  declarations: 
   { total: 383,
     unique: 273,
     properties: 
      { 'font-size': [Object],
        'font-family': [Object],
        'text-decoration': [Object],
        'font-weight': [Object],
        'font-style': [Object],
        'text-transform': [Object],
        'letter-spacing': [Object],
        'text-align': [Object],
        'white-space': [Object],
        'word-wrap': [Object],
        'line-height': [Object],
        'list-style': [Object],
        'max-width': [Object],
        overflow: [Object],
        'text-overflow': [Object],
        'padding-left': [Object],
        display: [Object],
        content: [Object],
        clear: [Object],
        float: [Object],
        'box-sizing': [Object],
        'vertical-align': [Object],
        margin: [Object],
        'margin-top': [Object],
        'margin-right': [Object],
        'margin-bottom': [Object],
        'margin-left': [Object],
        padding: [Object],
        'padding-top': [Object],
        'padding-right': [Object],
        'padding-bottom': [Object],
        width: [Object],
        '-webkit-box-orient': [Object],
        '-webkit-box-direction': [Object],
        '-webkit-flex-direction': [Object],
        '-ms-flex-direction': [Object],
        'flex-direction': [Object],
        '-webkit-flex-wrap': [Object],
        '-ms-flex-wrap': [Object],
        'flex-wrap': [Object],
        '-webkit-box-align': [Object],
        '-webkit-align-items': [Object],
        '-ms-flex-align': [Object],
        '-ms-grid-row-align': [Object],
        'align-items': [Object],
        '-webkit-align-self': [Object],
        '-ms-flex-item-align': [Object],
        'align-self': [Object],
        '-webkit-box-pack': [Object],
        '-webkit-justify-content': [Object],
        '-ms-flex-pack': [Object],
        'justify-content': [Object],
        '-webkit-align-content': [Object],
        '-ms-flex-line-pack': [Object],
        'align-content': [Object],
        '-webkit-box-flex': [Object],
        '-webkit-flex': [Object],
        '-ms-flex': [Object],
        flex: [Object],
        'min-width': [Object],
        'min-height': [Object],
        '-webkit-box-ordinal-group': [Object],
        '-webkit-order': [Object],
        '-ms-flex-order': [Object],
        order: [Object],
        position: [Object],
        top: [Object],
        right: [Object],
        bottom: [Object],
        left: [Object],
        'z-index': [Object],
        'border-style': [Object],
        'border-width': [Object],
        'border-top-style': [Object],
        'border-top-width': [Object],
        'border-right-style': [Object],
        'border-right-width': [Object],
        'border-bottom-style': [Object],
        'border-bottom-width': [Object],
        'border-left-style': [Object],
        'border-left-width': [Object],
        border: [Object],
        'border-radius': [Object],
        height: [Object],
        clip: [Object] },
     getPropertyResets: [Function],
     getUniquePropertyCount: [Function],
     getPropertyValueCount: [Function],
     getVendorPrefixed: [Function],
     getAllFontSizes: [Function],
     getAllFontFamilies: [Function] },
  mediaQueries: 
   { total: 10,
     unique: 6,
     values: 
      [ '(min-width:40em)',
        '(min-width:52em)',
        '(min-width:64em)',
        '(min-width:40em)',
        '(min-width:52em)',
        '(min-width:64em)',
        '(max-width:40em)',
        '(min-width:40em) and (max-width:52em)',
        '(min-width:52em) and (max-width:64em)',
        '(min-width:64em)' ],
     contents: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  toJSON: [Function] }
